apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "0"
  httpPipeline:
    handlers:
    - name: uppercase
      type: middleware.http.uppercase